---
- name: Converge
  hosts: all
  become: true

  vars:
    sftp_directories:
      - test1
      - test2
    sftp_users:
      - name: user1
        password: ""
        authorized: []
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=1200
      when: ansible_os_family == 'Debian'
      changed_when: false
    - name: Install openssl
      apt:
        name: ['openssh-server', 'openssh-client']
        update_cache: true
        cache_valid_time: 86400
  roles:
    - role: ansible-role-sftp
